# <center> Numpy Basics </center>

In [2]:
#import numpy module with alias np
import numpy as np

We can create a NumPy ndarray object by using the array() function.
To create an ndarray, we can pass a list, tuple or any array-like object into the array() method, and it will be converted into an ndarray:


In [5]:
# Define a numpy array passing a list with  1,2 and 3 as elements in it
my_list = [1, 2, 3]
arr_from_list = np.array(my_list)

In [6]:
# print output
print(arr_from_list)

[1 2 3]


## Dimensions in Arrays

Create arrays of different dimentions.

a=A numpy array with one single integer 10

b=A numpy array passing a list having a list= [1,2,3]

c=A numpy array passing nested list having [[1, 2, 3], [4, 5, 6]] as elements

d=A numpy array passing nested list having [[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]] as elements

In [7]:
#define a,b,c and d as instructed above

# a: A numpy array with one single integer 10
arr_a = np.array(10)
print("Array a:")
print(arr_a)

Array a:
10


In [8]:
# b: A numpy array passing a list having a list= [1,2,3]
arr_b = np.array([1, 2, 3])
print("\nArray b:")
print(arr_b)


Array b:
[1 2 3]


In [9]:
# c: A numpy array passing nested list having [[1, 2, 3], [4, 5, 6]] as elements
arr_c = np.array([[1, 2, 3], [4, 5, 6]])
print("\nArray c:")
print(arr_c)


Array c:
[[1 2 3]
 [4 5 6]]


In [10]:
# d: A numpy array passing nested list having [[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]] as elements
arr_d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print("\nArray d:")
print(arr_d)


Array d:
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


Are you ready to check its dimention? Use ndim attribute on each variable to check its dimention

In [11]:
#print dimentions of a,b, c and d

# a: A numpy array with one single integer 10
arr_a = np.array(10)
print("Array a:")
print(arr_a)
print("Dimensions of a:", arr_a.ndim)

Array a:
10
Dimensions of a: 0


In [59]:
# b: A numpy array passing a list having a list= [1,2,3]
arr_b = np.array([1, 2, 3])
print("\nArray b:")
print(arr_b)
print(arr_b.ndim)


Array b:
[1 2 3]
1


In [58]:
# c: A numpy array passing nested list having [[1, 2, 3], [4, 5, 6]] as elements
arr_c = np.array([[1, 2, 3], [4, 5, 6]])
print("\nArray c:")
print(arr_c)
print(arr_c.ndim)


Array c:
[[1 2 3]
 [4 5 6]]
2


In [57]:
# d: A numpy array passing nested list having [[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]] as elements
arr_d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr_d)
print(arr_d.ndim)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
3


Hey hey. Did you see! you have created 0-D,1-DeprecationWarning, 2-D and 3-D arrays.

Lets print there shape as well. You can check shape using shape attribute



Lets check data type passed in our array. To check data type you can use dtype attribute

In [56]:
# print data type of c and d

arr_c = np.array([[1, 2, 3], [4, 5, 6]])
print(arr_c)
print(arr_c.dtype)




[[1 2 3]
 [4 5 6]]
int64


In [55]:
arr_d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr_d)
print(arr_d.dtype)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
int64


Above output mean our array is having int type elements in it.

Lets check the type of our variable. To check type of any numpy variable use type() function

In [54]:
#print type of a and b variable
arr_a = np.array(10)
print(arr_a)
print(type(arr_a))

10
<class 'numpy.ndarray'>


In [53]:
arr_b = np.array([1, 2, 3])
print(arr_b)
print(type(arr_b))

[1 2 3]
<class 'numpy.ndarray'>


In [52]:
# Lets check length of array b, using len() function
# len(b)

arr_b = np.array([1, 2, 3])

length_of_b = len(arr_b.shape)

print(arr_b)
print(length_of_b)

[1 2 3]
1


Bravo!You have Defined ndarray i.e numpy array in variable a nd b. Also you have successfully learned how to create numpy.

Create two list l1 and l2 where, l1=[10,20,30] and l2=[40,50,60]
Also define two numpy arrays l3,l4 where l3 has l1 as element and l4 has l2 as element


In [51]:
# Define l1,l2,l3 and l4 as stated above.
# l1 =
# l2 =
# l3 =
# l4 =
l1 = [10, 20, 30]
l2 = [40, 50, 60]
l3 = np.array(l1)
l4 = np.array(l2)

print(l1)
print(l2)
print(l3)
print(l4)


[10, 20, 30]
[40, 50, 60]
[10 20 30]
[40 50 60]


Lets multiply each elements of l1 with corresponding elements of l2

Here use list comprehention to do so. Lets see how much you remember your work in other assignments.

Note: use %timeit as prefix before your line of code inorder to calculate total time taken to run that line<br>
eg. %timeit my_code

In [23]:
#code here as instructed above

%timeit result = [x * y for x, y in zip(l1, l2)]


714 ns ± 18.5 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [50]:
result = [x * y for x, y in zip(l1, l2)]
print(result)

[400, 1000, 1800]


Lets mulptiply l3 and l4

Note: use %timeit as prefix before your line of code inorder to calculate total time taken to run that line

In [49]:
%timeit result = l3 * l4

result = l3 * l4
print(result)


614 ns ± 10.6 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
[ 400 1000 1800]


Don't worry if still your one line of code is running. Its because your system is calculating total time taken to run your code.

Did you notice buddy! time taken to multiply two lists takes more time than multiplyimg two numpy array.
Hence proved that numpy arrays are faster than lists.

**Fun Fact time!:**

You know in many data science interviews it is asked that what is the difference between list and array.<br>


In [48]:
#Create a numpy array using a range with 1 and 11 as parameter in it

my_array = np.arange(1, 11)

print(my_array)


[ 1  2  3  4  5  6  7  8  9 10]


This means using arrange we get evenly spaced values within a given interval. Interval? Yes you can mention interval as well as third parameter in it.

In [47]:
# Create an array using arange passing 1,11 and 2 as parameter in iter

my_array = np.arange(1, 11, 2)

print(my_array)


[1 3 5 7 9]


In [46]:
# create numpy array using eye function with 3 as passed parameter

my_array = np.eye(3)

print(my_array)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [45]:
# Using arange() to generate numpy array x with numbers between 1 to 16
# x=

x = np.arange(1, 17)

print(x)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


In [44]:
# Reshape x with 2 rows and 8 columns
x = np.arange(1, 17)

reshaped_x = x.reshape(2, 8)

print(reshaped_x)


[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]


As you can see above that our x changed into 2D matrix

2. Reshaping 1-D to 3-D array


In [43]:
# reshaoe x with dimension that will have 2 arrays that contains 4 arrays, each with 2 elements:

x = np.arange(1, 17)

reshaped_x = x.reshape(2, 4, 2)

print(reshaped_x)


[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]
  [13 14]
  [15 16]]]


In [42]:
# Use unknown dimention to reshape x into 2-D numpy array with shape 4*4
x = np.arange(1, 17)

reshaped_x = x.reshape(4, -1)

print(reshaped_x)



[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [41]:
# Use unknown dimention to  reshape x into 3-D numpy array with 2 arrays that contains 4 arrays
# y=
x = np.arange(1, 17)

reshaped_y = x.reshape(2, 4, -1)
print(reshaped_y)


[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]
  [13 14]
  [15 16]]]


In [40]:
# Flattening y

flattened_y = reshaped_y.flatten()

print(flattened_y)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


In [61]:
# Create an array a with all even numbers between 1 to 17
# a =


# print a

a = np.arange(2,18,2)
print(a)


[ 2  4  6  8 10 12 14 16]


In [63]:
# Get third element in array a

a = np.arange(2, 18, 2)

third_element = a[2]

print("Third element in array a:", third_element)


Third element in array a: 6


In [64]:
#Print 3rd, 5th, and 7th element in array a

a = np.arange(2, 18, 2)

third_element = a[2]
fifth_element = a[4]
seventh_element = a[6]

print(third_element)
print(fifth_element)
print(seventh_element)


6
10
14


Lets check the same for 2 D array

In [65]:
# Define an array 2-D a with [[1,2,3],[4,5,6],[7,8,9]] as its elements.
# a =
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [66]:
# print the 3rd element from the 3rd row of a

element_3rd_row_3rd_col = a[2, 2]

print(element_3rd_row_3rd_col)

9


Well done!

Now lets check indexing for 3 D array

In [67]:
# Define an array b again with [[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]] as its elements.
# b =
b = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(b)


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [68]:
# Print 3rd element from 2nd list which is 1st list in nested list passed. Confusing right? 'a' have nested array.Understand the braket differences.

element_3rd_in_2nd_list = b[1, 0, 2]

print(element_3rd_in_2nd_list)


9


In [70]:
# Create 1D array

# arr=

arr = np.array([1, 2, 3, 4, 5])

print(arr)


[1 2 3 4 5]


In [75]:
# Slice elements from 1st to 5th element from the following array:

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

sliced_elements = arr[0:5]

print(sliced_elements)



[1 2 3 4 5]


Note: The result includes the start index, but excludes the end index.



In [76]:
# Slice elements from index 5 to the end of the array:

sliced_elements = arr[5:]

print(sliced_elements)


[ 6  7  8  9 10]


In [77]:
# Slice elements from the beginning to index 5 (not included):

sliced_elements = arr[:5]

print(sliced_elements)



[1 2 3 4 5]


**STEP**

Use the step value to determine the step of the slicing:

In [79]:
# Print every other element from index 1 to index 7:

every_other_element = arr[1:8:2]
print(every_other_element)


[2 4 6 8]


Did you see? using step you were able to get alternate elements within specified index numbers.

In [80]:
# Return every other element from the entire array arr:

every_other_element = arr[::2]

print(every_other_element)


[1 3 5 7 9]


well done!

Lets do some slicing on 2-D array also. We already have 'a' as our 2-D array. We will use it here.

**Array slicing in 2-D array.**

In [82]:
# Print array a

a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [84]:
# From the third element, slice elements from index 1 to index 5 (not included) from array 'a'

sliced_elements = a[2, 1:5]

print(sliced_elements)


[8 9]


In [86]:
# In array 'a' print index 2 from all the elements :

index_2_elements = a[:, 2]

print(index_2_elements)


[3 6 9]


In [88]:
# From all the elements in 'a', slice index 1 till end, this will return a 2-D array:

sliced_elements = a[:, 1:]

print(sliced_elements)


[[2 3]
 [5 6]
 [8 9]]


Hurray! You have learned Slicing in Numpy array. Now you know to access any numpy array.

## Numpy copy vs view

In [90]:
# x1=
original_array = np.array([1, 2, 3, 4, 5])

x1_copy = np.copy(original_array)

x1_copy[0] = 99

print(original_array)
print(x1_copy)


[1 2 3 4 5]
[99  2  3  4  5]


In [91]:
# assign x2 = x1
x1 = np.array([10, 20, 30, 40, 50])

x2 = x1

x2[0] = 99

print(x1)
print(x2)


[99 20 30 40 50]
[99 20 30 40 50]


Ok now you have seen that both of them are same

In [94]:
# change 1st element of x2 as 10
x2 = x1

x2[0] = 10


In [95]:
#Again print x1 and x2

print(x1)
print(x2)


[10 20 30 40 50]
[10 20 30 40 50]


In [96]:
# Check memory share between x1 and x2

share_memory = np.shares_memory(x1, x2)

print(share_memory)


True


Hey It's True they both share memory

Shall we try **view()** function also likwise.

In [98]:
# Create a view of x1 and store it in x3.
# x3 =
x3 = x1.view()

print(x1)
print(x3)

[10 20 30 40 50]
[10 20 30 40 50]


In [99]:
# Again check memory share between x1 and x3

share_memory = np.shares_memory(x1, x3)

print(share_memory)


True


Woh! simple assignment is similar to view. That means
The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.

Don't agree? ok lets change x3 and see if original array i.e. x1 also changes

In [100]:
#Change 1st element of x3=100
x3[0] = 100

print(x1)
print(x3)


[100  20  30  40  50]
[100  20  30  40  50]


In [101]:
#print x1 and x3 to check if changes reflected in both
x3[0] = 100

print(x1)
print(x3)


[100  20  30  40  50]
[100  20  30  40  50]


Now its proved.

Lets see how **Copy()** function works

In [102]:
# Now create an array x4 which is copy of x1

# x4=
x4 = np.copy(x1)

print(x1)
print(x4)


[100  20  30  40  50]
[100  20  30  40  50]


In [104]:
# Change the last element of x4 as 900

x4[-1] = 900

print(x4)



[100  20  30  40 900]


In [105]:
# print both x1 and x4 to check if changes reflected in both


print(x1)
print(x4)


[100  20  30  40  50]
[100  20  30  40 900]


Hey! such an intresting output. You noticed buddy! your original array didn't get changed on change of its copy ie. x4.

Still not convinced? Ok lets see if they both share memory or not

In [106]:
#Check memory share between x1 and x4

share_memory = np.shares_memory(x1, x4)

print(share_memory)


False


**hstack vs vstack function**


Stacking is same as concatenation, the only difference is that stacking is done along a new axis.

NumPy provides a helper function:

1. hstack() to stack along rows.
2. vstack()  to stack along columns

In [107]:
# stack x1 and x4 along columns.

stacked_array = np.column_stack((x1, x4))

print(stacked_array)

[[100 100]
 [ 20  20]
 [ 30  30]
 [ 40  40]
 [ 50 900]]


In [108]:
#stack x1 and x4 along rows
stacked_array = np.row_stack((x1, x4))

print(stacked_array)


[[100  20  30  40  50]
 [100  20  30  40 900]]


We hope now you saw the difference between them.

Fun fact! you can even use concatenate() function to join 2 arrays along with the axis. If axis is not explicitly passed, it is taken as 0 ie. along column

Lets try this function as well

In [110]:
# arr1 =


# arr2 =


##join arr1 and arr2 along rows using concatenate() function

arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])

concatenated_array = np.concatenate((arr1, arr2), axis=0)

print(concatenated_array)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [111]:
##join arr1 and arr2 along columns using concatenate() function

concatenated_array = np.concatenate((arr1, arr2), axis=1)

print(concatenated_array)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


## Adding, Insert and delete Numpy array

You can also add 2 arrays using append() function also. This function appends values to end of array

Lets see how

In [113]:
# append arr2 to arr1
appended_array = np.append(arr1, arr2, axis=0)
print(appended_array)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


Lets use insert() function which Inserts values into array before specified index value

In [114]:
# Inserts values into array x1 before index 4 with elements of x4

x1 = np.array([100, 20, 30, 40, 50])

x4 = np.array([900, 800, 700])

result_array = np.insert(x1, 4, x4)

print(x1)
print(x4)
print(result_array)

[100  20  30  40  50]
[900 800 700]
[100  20  30  40 900 800 700  50]


You can see in above output we have inserted all the elements of x4 before index 4 in array x1.

In [116]:
# delete 2nd element from array x2

result_array = np.delete(x2, 1)

print(x2)
print(result_array)


[100  20  30  40  50]
[100  30  40  50]


Did you see? 2 value is deleted from x2 which was at index position 2

Good Job learner!